#pragma once
#include "sdkconfig.h"

#if CONFIG_FREERTOS_HZ < 1000
#error "Bridge 1 ms polling requires CONFIG_FREERTOS_HZ=1000 to avoid zero-tick busy loops."
#endif

/* Pair-specific material is generated by firmware/tools/provision.py. */
#if defined(CONFIG_BRIDGE_TEST_FIXTURE) && CONFIG_BRIDGE_TEST_FIXTURE
#include "pair_config.h.example"
#define BRIDGE_NONDEPLOYABLE_FIXTURE 1
#elif __has_include("pair_config.h")
#include "pair_config.h"
#else
#error "Missing config/private/pair_config.h. Provision the physical pair before building deployable firmware."
#endif

#if !defined(BRIDGE_ROLE_A) && !defined(BRIDGE_ROLE_B)
#error "A bridge role must be selected by the target CMake project."
#endif
#if defined(BRIDGE_ROLE_A) && defined(BRIDGE_ROLE_B)
#error "A firmware image can have only one bridge role."
#endif
